name: Delta Dev
favicon: null
layout_spectrum: 0
typography_spectrum: 0.27349
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f2f2f'
    - '#71cac7'
    - '#568c8a'
    - '#fcfcfc'
    - '#a1a1a1'
  brandStrength: 0.3966032250318676
  lightness: 0.0749541234690696
  saturation: 0.6933527877554297
  rhythmicContrast: 0.49793289857916534
purpose: []
