name: Delta Dev
favicon: null
layout_spectrum: 0.6814764435403049
typography_spectrum: 0.5889208244625479
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3966032250318676
  lightness: 0.0749541234690696
  saturation: 0.6933527877554297
  rhythmicContrast: 0.49793289857916534
purpose: []
